#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Sat May  9 21:24:17 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class devFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: devFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.output0 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.HSCROLL | wx.TE_MULTILINE | wx.TE_READONLY)
        self.ch0_L = wx.ToggleButton(self, wx.ID_ANY, _("ch0_L"))
        self.ch1_L = wx.ToggleButton(self, wx.ID_ANY, _("ch1_L"))
        self.ch2_L = wx.ToggleButton(self, wx.ID_ANY, _("ch2_L"))
        self.ch3_L = wx.ToggleButton(self, wx.ID_ANY, _("ch3_L"))
        self.ch4_L = wx.ToggleButton(self, wx.ID_ANY, _("ch4_L"))
        self.ch5_L = wx.ToggleButton(self, wx.ID_ANY, _("ch5_L"))
        self.ch6_L = wx.ToggleButton(self, wx.ID_ANY, _("ch6_L"))
        self.ch7_L = wx.ToggleButton(self, wx.ID_ANY, _("ch7_L"))
        self.ch0_H = wx.ToggleButton(self, wx.ID_ANY, _("ch0_H"))
        self.ch1_H = wx.ToggleButton(self, wx.ID_ANY, _("ch1_H"))
        self.ch2_H = wx.ToggleButton(self, wx.ID_ANY, _("ch2_H"))
        self.ch3_H = wx.ToggleButton(self, wx.ID_ANY, _("ch3_H"))
        self.ch4_H = wx.ToggleButton(self, wx.ID_ANY, _("ch4_H"))
        self.ch5_H = wx.ToggleButton(self, wx.ID_ANY, _("ch5_H"))
        self.ch6_H = wx.ToggleButton(self, wx.ID_ANY, _("ch6_H"))
        self.ch7_H = wx.ToggleButton(self, wx.ID_ANY, _("ch7_H"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch0_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch1_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch2_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch3_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch4_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch5_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch6_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch7_L)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch0_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch1_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch2_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch3_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch4_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch5_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch6_H)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.showCh, self.ch7_H)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: devFrame.__set_properties
        self.SetTitle(_("dev0"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: devFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(2, 8, 1, 1)
        sizer_1.Add(self.output0, 2, wx.EXPAND, 0)
        grid_sizer_1.Add(self.ch0_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch1_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch2_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch3_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch4_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch5_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch6_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch7_L, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch0_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch1_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch2_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch3_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch4_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch5_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch6_H, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.ch7_H, 1, wx.ALL | wx.EXPAND, 1)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL, 1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def showCh(self, event):  # wxGlade: devFrame.<event_handler>
        print "Event handler 'showCh' not implemented!"
        event.Skip()

# end of class devFrame
class devApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        dev0 = devFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(dev0)
        dev0.Show()
        return 1

# end of class devApp

if __name__ == "__main__":
    gettext.install("dev0") # replace with the appropriate catalog name

    dev0 = devApp(0)
    dev0.MainLoop()