#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Sat Apr 25 06:38:47 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class smFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: smFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: smFrame.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: smFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class smFrame
#class smApp(wx.App):
#    def OnInit(self):
#        wx.InitAllImageHandlers()
#        sm = smFrame(None, wx.ID_ANY, "")
#        self.SetTopWindow(sm)
#        sm.Show()
#        return 1

# end of class smApp

if __name__ == "__main__":
    gettext.install("sm") # replace with the appropriate catalog name

    sm = smApp(0)
    sm.MainLoop()
